### ISSUE TITLE
Integers fail to decode as floats

### ISSUE THREAD

**Issue by nup002** [mitsuse/typedjson-python#10]
In python static typing, integers are defined as being a subset of floats. In other words, you can do the following and it will not fail a Mypy check:
```
bar:float = 1.0 #Define bar as a float
bar = 1 #Assign an integer
```
I believe it is therefore natural to expect a json string given as an integer to not fail to be parsed into a class where the variable has been defined as a float. Take for example the following dataclass that has a single float variable defined:
```
@dataclass
class FloatVariable():
    var:float = 1.0
```
Trying to decode the following json string will fail with `<DecodingError reason=<TypeMismatch path=('var',)>>`:
```
{
  "var": 1
}
```

The reason I bring this up is that I have users who will be editing json-files which gets loaded into dataclasses in exactly this manner. There are variables which are defined as floats in the dataclasses, but users are very likely to write them as integers in the json files. It is unreasonable to demand from the users that they never define variables as integers in the json files. After all, there is no difference between 1 and 1.0 from the users perspective.

**Comment by mitsuse** [comment]
@nup002 Thank you for suggestion. Please use the version 0.10.3 which fixed this issue. Your suggestion is right to the point. Also in terms of the JSON specification, I saw no reason to not accept int as a float.
